### ISSUE TITLE
环境配置的分类

### ISSUE THREAD

**Issue by wznmickey** [fstqwq/AI2615#1]
现在环境配置部分按照LInux/Win/MacOS分成了三类，但是 Linux下的内容和win下的内容其实不太和系统相关联。
比如，linux下介绍了命令行的编译方式，但是在win中使用mingw的情况下也可以使用命令行进行操作。
再比如，win下的IDE基本也都提供linux版本，即使在使用linux的同学中，这些软件使用同学也不少，纯vi的同学应该非常少。

是否可以考虑分成与系统环境相关和与系统环境无关两部分进行介绍。比如命令行/IDE之类的在三个系统中都有需要，而相关工具的安装在不同系统中不一样，比如linux下通常是使用对应的包管理器，win中可以用mingw/IDE自带/包管理器/虚拟Linux环境。

**Comment by fstqwq** [comment]
搞定。

但是问题在于有些内容我自己也没了解，还有一些没有写，留了不少空。

**Comment by wznmickey** [comment]
自动回复：已收到，谢谢。
